//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomateBarcode.TissueManagement {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://resources.axis.webservice.tissuebank.scbit.org", ConfigurationName="TissueManagement.ResourcesPortType")]
    public interface ResourcesPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:PrintBarcodes", ReplyAction="urn:PrintBarcodesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AutomateBarcode.TissueManagement.PrintBarcodesResponse PrintBarcodes(AutomateBarcode.TissueManagement.PrintBarcodesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="urn:UpdatePackageInfo", ReplyAction="urn:UpdatePackageInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        AutomateBarcode.TissueManagement.UpdatePackageInfoResponse UpdatePackageInfo(AutomateBarcode.TissueManagement.UpdatePackageInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.axis.webservice.tissuebank.scbit.org/xsd")]
    public partial class PrintResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] barcodesField;
        
        private System.Nullable<bool> bokField;
        
        private bool bokFieldSpecified;
        
        private string errDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("barcodes", IsNullable=true, Order=0)]
        public string[] barcodes {
            get {
                return this.barcodesField;
            }
            set {
                this.barcodesField = value;
                this.RaisePropertyChanged("barcodes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<bool> bok {
            get {
                return this.bokField;
            }
            set {
                this.bokField = value;
                this.RaisePropertyChanged("bok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bokSpecified {
            get {
                return this.bokFieldSpecified;
            }
            set {
                this.bokFieldSpecified = value;
                this.RaisePropertyChanged("bokSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string errDescription {
            get {
                return this.errDescriptionField;
            }
            set {
                this.errDescriptionField = value;
                this.RaisePropertyChanged("errDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.axis.webservice.tissuebank.scbit.org/xsd")]
    public partial class UpdateResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<bool> bokField;
        
        private bool bokFieldSpecified;
        
        private string errDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<bool> bok {
            get {
                return this.bokField;
            }
            set {
                this.bokField = value;
                this.RaisePropertyChanged("bok");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool bokSpecified {
            get {
                return this.bokFieldSpecified;
            }
            set {
                this.bokFieldSpecified = value;
                this.RaisePropertyChanged("bokSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string errDescription {
            get {
                return this.errDescriptionField;
            }
            set {
                this.errDescriptionField = value;
                this.RaisePropertyChanged("errDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1015")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://bean.axis.webservice.tissuebank.scbit.org/xsd")]
    public partial class TubeInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string barcodeField;
        
        private string sampleTypeField;
        
        private string sliceIDField;
        
        private string srcBarcodeField;
        
        private string volumeULField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                this.barcodeField = value;
                this.RaisePropertyChanged("barcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string sampleType {
            get {
                return this.sampleTypeField;
            }
            set {
                this.sampleTypeField = value;
                this.RaisePropertyChanged("sampleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string sliceID {
            get {
                return this.sliceIDField;
            }
            set {
                this.sliceIDField = value;
                this.RaisePropertyChanged("sliceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string srcBarcode {
            get {
                return this.srcBarcodeField;
            }
            set {
                this.srcBarcodeField = value;
                this.RaisePropertyChanged("srcBarcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string volumeUL {
            get {
                return this.volumeULField;
            }
            set {
                this.volumeULField = value;
                this.RaisePropertyChanged("volumeUL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintBarcodes", WrapperNamespace="http://resources.axis.webservice.tissuebank.scbit.org", IsWrapped=true)]
    public partial class PrintBarcodesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resources.axis.webservice.tissuebank.scbit.org", Order=0)]
        public int totalCnt;
        
        public PrintBarcodesRequest() {
        }
        
        public PrintBarcodesRequest(int totalCnt) {
            this.totalCnt = totalCnt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PrintBarcodesResponse", WrapperNamespace="http://resources.axis.webservice.tissuebank.scbit.org", IsWrapped=true)]
    public partial class PrintBarcodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resources.axis.webservice.tissuebank.scbit.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AutomateBarcode.TissueManagement.PrintResult @return;
        
        public PrintBarcodesResponse() {
        }
        
        public PrintBarcodesResponse(AutomateBarcode.TissueManagement.PrintResult @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePackageInfo", WrapperNamespace="http://resources.axis.webservice.tissuebank.scbit.org", IsWrapped=true)]
    public partial class UpdatePackageInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resources.axis.webservice.tissuebank.scbit.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("infos", IsNullable=true)]
        public TubeInfo[] infos;
        
        public UpdatePackageInfoRequest() {
        }
        
        public UpdatePackageInfoRequest(TubeInfo[] infos) {
            this.infos = infos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdatePackageInfoResponse", WrapperNamespace="http://resources.axis.webservice.tissuebank.scbit.org", IsWrapped=true)]
    public partial class UpdatePackageInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://resources.axis.webservice.tissuebank.scbit.org", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public AutomateBarcode.TissueManagement.UpdateResult @return;
        
        public UpdatePackageInfoResponse() {
        }
        
        public UpdatePackageInfoResponse(AutomateBarcode.TissueManagement.UpdateResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ResourcesPortTypeChannel : AutomateBarcode.TissueManagement.ResourcesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResourcesPortTypeClient : System.ServiceModel.ClientBase<AutomateBarcode.TissueManagement.ResourcesPortType>, AutomateBarcode.TissueManagement.ResourcesPortType {
        
        public ResourcesPortTypeClient() {
        }
        
        public ResourcesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResourcesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourcesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResourcesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutomateBarcode.TissueManagement.PrintBarcodesResponse AutomateBarcode.TissueManagement.ResourcesPortType.PrintBarcodes(AutomateBarcode.TissueManagement.PrintBarcodesRequest request) {
            return base.Channel.PrintBarcodes(request);
        }
        
        public AutomateBarcode.TissueManagement.PrintResult PrintBarcodes(int totalCnt) {
            AutomateBarcode.TissueManagement.PrintBarcodesRequest inValue = new AutomateBarcode.TissueManagement.PrintBarcodesRequest();
            inValue.totalCnt = totalCnt;
            AutomateBarcode.TissueManagement.PrintBarcodesResponse retVal = ((AutomateBarcode.TissueManagement.ResourcesPortType)(this)).PrintBarcodes(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AutomateBarcode.TissueManagement.UpdatePackageInfoResponse AutomateBarcode.TissueManagement.ResourcesPortType.UpdatePackageInfo(AutomateBarcode.TissueManagement.UpdatePackageInfoRequest request) {
            return base.Channel.UpdatePackageInfo(request);
        }
        
        public AutomateBarcode.TissueManagement.UpdateResult UpdatePackageInfo(TubeInfo[] infos) {
            AutomateBarcode.TissueManagement.UpdatePackageInfoRequest inValue = new AutomateBarcode.TissueManagement.UpdatePackageInfoRequest();
            inValue.infos = infos;
            AutomateBarcode.TissueManagement.UpdatePackageInfoResponse retVal = ((AutomateBarcode.TissueManagement.ResourcesPortType)(this)).UpdatePackageInfo(inValue);
            return retVal.@return;
        }
    }
}
