//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testharness.BiobankService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TubeInfo", Namespace="http://model.service.tecan.bio.haiersoft.com")]
    [System.SerializableAttribute()]
    public partial class TubeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string barcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sampleTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sliceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string srcBarcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string volumeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string barcode {
            get {
                return this.barcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.barcodeField, value) != true)) {
                    this.barcodeField = value;
                    this.RaisePropertyChanged("barcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sampleType {
            get {
                return this.sampleTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.sampleTypeField, value) != true)) {
                    this.sampleTypeField = value;
                    this.RaisePropertyChanged("sampleType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sliceID {
            get {
                return this.sliceIDField;
            }
            set {
                if ((object.ReferenceEquals(this.sliceIDField, value) != true)) {
                    this.sliceIDField = value;
                    this.RaisePropertyChanged("sliceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string srcBarcode {
            get {
                return this.srcBarcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.srcBarcodeField, value) != true)) {
                    this.srcBarcodeField = value;
                    this.RaisePropertyChanged("srcBarcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string volume {
            get {
                return this.volumeField;
            }
            set {
                if ((object.ReferenceEquals(this.volumeField, value) != true)) {
                    this.volumeField = value;
                    this.RaisePropertyChanged("volume");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateResult", Namespace="http://model.service.tecan.bio.haiersoft.com")]
    [System.SerializableAttribute()]
    public partial class UpdateResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string batchIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isOkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string batchID {
            get {
                return this.batchIDField;
            }
            set {
                if ((object.ReferenceEquals(this.batchIDField, value) != true)) {
                    this.batchIDField = value;
                    this.RaisePropertyChanged("batchID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string errMessage {
            get {
                return this.errMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errMessageField, value) != true)) {
                    this.errMessageField = value;
                    this.RaisePropertyChanged("errMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isOk {
            get {
                return this.isOkField;
            }
            set {
                if ((this.isOkField.Equals(value) != true)) {
                    this.isOkField = value;
                    this.RaisePropertyChanged("isOk");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://service.tecan.bio.haiersoft.com", ConfigurationName="BiobankService.IBiobankExternalServicePortType")]
    public interface IBiobankExternalServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        Testharness.BiobankService.UpdateResult updatePackageInfo(Testharness.BiobankService.TubeInfo[] in0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBiobankExternalServicePortTypeChannel : Testharness.BiobankService.IBiobankExternalServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BiobankExternalServicePortTypeClient : System.ServiceModel.ClientBase<Testharness.BiobankService.IBiobankExternalServicePortType>, Testharness.BiobankService.IBiobankExternalServicePortType {
        
        public BiobankExternalServicePortTypeClient() {
        }
        
        public BiobankExternalServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BiobankExternalServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiobankExternalServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BiobankExternalServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Testharness.BiobankService.UpdateResult updatePackageInfo(Testharness.BiobankService.TubeInfo[] in0) {
            return base.Channel.updatePackageInfo(in0);
        }
    }
}
